# 
# Hls run script generated by SDAccel
# 

set xocc_optimize_level 0
open_project gemxKernel_0
set_top gemxKernel_0
config_debug 
add_files "/home/centos/src/project_data/aws-fpga/git/gemxx-2017/gemx/src/gemx_kernel.cpp" -cflags " -g -D GMEM_M=0 -D TEST_SDX=1 -D GEMX_dataType=short -D GEMX_XdataType=int32_t -D GEMX_dataEqIntType=short -D GEMX_ddrWidth=32 -D GEMX_XddrWidth=16 -D GEMX_argInstrWidth=1 -D GEMX_numInstr=16 -D GEMX_gemvkVectorBlocks=512 -D GEMX_gemvmVectorBlocks=512 -D GEMX_gemvmGroups=1 -D GEMX_gemmMBlocks=1 -D GEMX_gemmKBlocks=2 -D GEMX_gemmNBlocks=1 -D GEMX_keepMacBits=0 -D GEMX_macBits=48 -D GEMX_transpBlocks=1 -D GEMX_spmvWidth=8 -D GEMX_spmvkVectorBlocks=2048 -D GEMX_spmvMacGroups=12 -D GEMX_spmvColAddIdxBits=2 -D GEMX_spmvPadA=1 -D GEMX_spmvNumCblocks=1024 -D GEMX_spmvFloatPerDesc=4 -D GEMX_idxType=int32_t -D GEMX_nnzBlocks=8 -D GEMX_spmvKmaxBlocks=32768 -D GEMX_spmvMmaxBlocks=5462 -D GEMX_spmvUramGroups=6 -D GEMX_argPipeline=2 -D GEMX_part=vu9pf1 -D GEMX_useURAM=0 -D GEMX_splitMesh=0 -D GEMX_runGemv=0 -D GEMX_runGemm=1 -D GEMX_runTransp=0 -D GEMX_runSpmv=0 -D GEMX_numKernels=1 -D GEMX_kernelId=0 -I /home/centos/src/project_data/aws-fpga/git/gemxx-2017/gemx/src -I /home/centos/src/project_data/aws-fpga/git/gemxx-2017/gemx/src/python -std=c++0x "
open_solution solution_OCL_REGION_0
set_part xcvu9p-flgb2104-2-i
create_clock -period 250MHz -name default
set_clock_uncertainty 1.080000
config_rtl -register_reset
config_interface -m_axi_addr64
config_schedule -relax_ii_for_timing
config_compile -pipeline_loops 64
config_compile -name_max_length 256
config_rtl -prefix gemxKernel_0_
csynth_design -skip_transform
close_project
puts "Vivado HLS completed successfully"
exit
